[2025-06-16T15:47:01.336+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:47:01.398+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-16T15:47:01.426+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:47:01.434+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-16T15:47:01.444+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-16T15:47:01.489+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-16T15:47:01.490+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-16T15:47:01.491+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T15:47:01.491+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T15:47:01.506+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [queued]>
[2025-06-16T15:47:01.521+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-16T15:47:01.522+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-16T15:47:01.523+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-16T15:47:01.524+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-16T15:47:01.538+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [queued]>
[2025-06-16T15:47:01.539+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-16T15:47:01.563+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_locations> on 2025-06-16 15:46:44.299425+00:00
[2025-06-16T15:47:01.585+0000] {standard_task_runner.py:63} INFO - Started process 389 to run task
[2025-06-16T15:47:01.592+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_locations', 'manual__2025-06-16T15:46:44.299425+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmp545h5ehs']
[2025-06-16T15:47:01.595+0000] {standard_task_runner.py:91} INFO - Job 114: Subtask transform.transform_dim_locations
[2025-06-16T15:47:01.597+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7fa267925750>]
[2025-06-16T15:47:01.703+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:47:01.713+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_locations manual__2025-06-16T15:46:44.299425+00:00 [running]> on host 9b7c60adfed6
[2025-06-16T15:47:01.715+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 389)
[2025-06-16T15:47:01.716+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 389)
[2025-06-16T15:47:01.717+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-16T15:47:01.820+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-16T15:47:01.826+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-16T15:47:01.868+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-16T15:47:01.916+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-16T15:47:01.943+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_locations' AIRFLOW_CTX_EXECUTION_DATE='2025-06-16T15:46:44.299425+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-16T15:46:44.299425+00:00'
[2025-06-16T15:47:01.945+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-16T15:47:01.947+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-16T15:47:01.948+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-16T15:47:02.606+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T15:47:02.628+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T15:47:02.643+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-16T15:47:02.659+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-16T15:47:03.499+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_location
[2025-06-16T15:47:03.510+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-16T15:47:03.512+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-16T15:47:03.513+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-16T15:47:03.526+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-16T15:47:03.527+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_locations, run_id=manual__2025-06-16T15:46:44.299425+00:00, execution_date=20250616T154644, start_date=20250616T154701, end_date=20250616T154703
[2025-06-16T15:47:03.527+0000] {taskinstance.py:562} DEBUG - Task Duration set to 2.017362
[2025-06-16T15:47:03.538+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-16T15:47:03.554+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-16T15:47:03.575+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-16 15:46:44.299425+00:00: manual__2025-06-16T15:46:44.299425+00:00, state:running, queued_at: 2025-06-16 15:46:44.370673+00:00. externally triggered: True>: 6 task(s)
[2025-06-16T15:47:03.576+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-16 15:46:44.299425+00:00: manual__2025-06-16T15:46:44.299425+00:00, state:running, queued_at: 2025-06-16 15:46:44.370673+00:00. externally triggered: True>: 0 task(s)
[2025-06-16T15:47:03.576+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-16T15:47:03.579+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
