[2025-06-15T16:50:39.534+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-15T16:50:39.605+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-15T16:50:39.644+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-15T16:50:39.668+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-15T16:50:39.685+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-15T16:50:39.775+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-15T16:50:39.776+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:39.777+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-15T16:50:39.779+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:39.779+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [queued]>
[2025-06-15T16:50:39.791+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-15T16:50:39.801+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-15T16:50:39.803+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:39.804+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:39.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [queued]>
[2025-06-15T16:50:39.805+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-15T16:50:39.834+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_products> on 2025-06-15 16:50:05.830452+00:00
[2025-06-15T16:50:39.860+0000] {standard_task_runner.py:63} INFO - Started process 583 to run task
[2025-06-15T16:50:39.869+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_products', 'manual__2025-06-15T16:50:05.830452+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmpchyxeeng']
[2025-06-15T16:50:39.872+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask transform.transform_dim_products
[2025-06-15T16:50:39.874+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7fd327729750>]
[2025-06-15T16:50:39.966+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-15T16:50:39.984+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_products manual__2025-06-15T16:50:05.830452+00:00 [running]> on host a40e01b9e58f
[2025-06-15T16:50:39.985+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 583)
[2025-06-15T16:50:39.986+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 583)
[2025-06-15T16:50:39.987+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-15T16:50:40.065+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-15T16:50:40.080+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-15T16:50:40.119+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-15T16:50:40.178+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-15T16:50:40.211+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_products' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T16:50:05.830452+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-15T16:50:05.830452+00:00'
[2025-06-15T16:50:40.213+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-15T16:50:40.215+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-15T16:50:40.217+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-15T16:50:40.285+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T16:50:40.309+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T16:50:40.350+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T16:50:40.377+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T16:50:40.518+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T16:50:40.555+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T16:50:40.622+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-15T16:50:40.653+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-15T16:50:43.351+0000] {logging_mixin.py:188} INFO - ✔ Đã transform và lưu dữ liệu vào warehouse.dim_product
[2025-06-15T16:50:43.353+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-15T16:50:43.355+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-15T16:50:43.356+0000] {__init__.py:77} DEBUG - Lineage called with inlets: [], outlets: []
[2025-06-15T16:50:43.365+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-15T16:50:43.366+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=globalsuperstore, task_id=transform.transform_dim_products, run_id=manual__2025-06-15T16:50:05.830452+00:00, execution_date=20250615T165005, start_date=20250615T165039, end_date=20250615T165043
[2025-06-15T16:50:43.366+0000] {taskinstance.py:562} DEBUG - Task Duration set to 3.586025
[2025-06-15T16:50:43.379+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-15T16:50:43.412+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-15T16:50:43.434+0000] {dagrun.py:931} DEBUG - number of tis tasks for <DagRun globalsuperstore @ 2025-06-15 16:50:05.830452+00:00: manual__2025-06-15T16:50:05.830452+00:00, state:running, queued_at: 2025-06-15 16:50:06.195501+00:00. externally triggered: True>: 6 task(s)
[2025-06-15T16:50:43.435+0000] {dagrun.py:952} DEBUG - number of scheduleable tasks for <DagRun globalsuperstore @ 2025-06-15 16:50:05.830452+00:00: manual__2025-06-15T16:50:05.830452+00:00, state:running, queued_at: 2025-06-15 16:50:06.195501+00:00. externally triggered: True>: 1 task(s)
[2025-06-15T16:50:43.435+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-15T16:50:43.436+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-15T16:50:05.830452+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-15T16:50:43.437+0000] {taskinstance.py:2076} DEBUG - Dependencies all met for dep_context=None ti=<TaskInstance: globalsuperstore.load.transform_fact_sales manual__2025-06-15T16:50:05.830452+00:00 [None]>
[2025-06-15T16:50:43.441+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-15T16:50:43.445+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
