[2025-06-13T17:17:15.967+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-13T17:17:16.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: GlobalSuperStore_dw_etl.extract.extract_and_load_to_staging manual__2025-06-13T17:17:15.183314+00:00 [queued]>
[2025-06-13T17:17:16.029+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: GlobalSuperStore_dw_etl.extract.extract_and_load_to_staging manual__2025-06-13T17:17:15.183314+00:00 [queued]>
[2025-06-13T17:17:16.029+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-13T17:17:16.050+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract.extract_and_load_to_staging> on 2025-06-13 17:17:15.183314+00:00
[2025-06-13T17:17:16.062+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'GlobalSuperStore_dw_etl', 'extract.extract_and_load_to_staging', 'manual__2025-06-13T17:17:15.183314+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/globalSuperstore.py', '--cfg-path', '/tmp/tmpnccgskrf']
[2025-06-13T17:17:16.069+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask extract.extract_and_load_to_staging
[2025-06-13T17:17:16.057+0000] {standard_task_runner.py:63} INFO - Started process 396 to run task
[2025-06-13T17:17:16.204+0000] {task_command.py:426} INFO - Running <TaskInstance: GlobalSuperStore_dw_etl.extract.extract_and_load_to_staging manual__2025-06-13T17:17:15.183314+00:00 [running]> on host ce8c7e7a2a87
[2025-06-13T17:17:16.617+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='GlobalSuperStore_dw_etl' AIRFLOW_CTX_TASK_ID='extract.extract_and_load_to_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T17:17:15.183314+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-13T17:17:15.183314+00:00'
[2025-06-13T17:17:16.619+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-13T17:17:16.666+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2025-06-13T17:17:16.695+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-06-13T17:17:16.717+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-13T17:17:16.730+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-13T17:17:16.730+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidSchemaName: schema "staging" does not exist
LINE 2: CREATE TABLE staging."stg_Category" (
                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract_data.py", line 30, in extract_and_load_to_staging
    staging_operator.save_data_to_postgres(
  File "/opt/airflow/plugins/postgresql_operator.py", line 19, in save_data_to_postgres
    df.to_sql(table_name, engine, schema=schema, if_exists=if_exists, index=False)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 2987, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 695, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 1728, in to_sql
    table = self.prep_table(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 1631, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 838, in create
    self._execute_create()
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 824, in _execute_create
    self.table.create(bind=self.pd_sql.connectable)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 962, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3238, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 899, in visit_table
    self.connection.execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) schema "staging" does not exist
LINE 2: CREATE TABLE staging."stg_Category" (
                     ^

[SQL: 
CREATE TABLE staging."stg_Category" (
	category_id BIGINT, 
	category_name TEXT
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-06-13T17:17:16.748+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=GlobalSuperStore_dw_etl, task_id=extract.extract_and_load_to_staging, run_id=manual__2025-06-13T17:17:15.183314+00:00, execution_date=20250613T171715, start_date=20250613T171716, end_date=20250613T171716
[2025-06-13T17:17:16.762+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task extract.extract_and_load_to_staging ((psycopg2.errors.InvalidSchemaName) schema "staging" does not exist
LINE 2: CREATE TABLE staging."stg_Category" (
                     ^

[SQL: 
CREATE TABLE staging."stg_Category" (
	category_id BIGINT, 
	category_name TEXT
)

]
(Background on this error at: https://sqlalche.me/e/14/f405); 396)
[2025-06-13T17:17:16.806+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-13T17:17:16.821+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-13T17:17:16.832+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
