[2025-06-17T02:50:16.532+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:50:16.597+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2025-06-17T02:50:16.614+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:50:16.620+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2025-06-17T02:50:16.645+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-17T02:50:16.798+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-06-17T02:50:16.799+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:50:16.799+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-06-17T02:50:16.808+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:50:16.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [queued]>
[2025-06-17T02:50:16.816+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-06-17T02:50:16.817+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-06-17T02:50:16.818+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-06-17T02:50:16.822+0000] {taskinstance.py:2088} DEBUG - <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-06-17T02:50:16.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [queued]>
[2025-06-17T02:50:16.823+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-06-17T02:50:16.856+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_shipmode> on 2025-06-17 02:49:44.133467+00:00
[2025-06-17T02:50:16.883+0000] {standard_task_runner.py:63} INFO - Started process 228 to run task
[2025-06-17T02:50:16.889+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'globalsuperstore', 'transform.transform_dim_shipmode', 'manual__2025-06-17T02:49:44.133467+00:00', '--job-id', '445', '--raw', '--subdir', 'DAGS_FOLDER/global_superstore_dw_etl.py', '--cfg-path', '/tmp/tmp1wfzl52j']
[2025-06-17T02:50:16.891+0000] {standard_task_runner.py:91} INFO - Job 445: Subtask transform.transform_dim_shipmode
[2025-06-17T02:50:16.892+0000] {cli_action_loggers.py:70} DEBUG - Calling callbacks: [<function default_action_log at 0x7f9296139750>]
[2025-06-17T02:50:16.959+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:50:16.964+0000] {task_command.py:426} INFO - Running <TaskInstance: globalsuperstore.transform.transform_dim_shipmode manual__2025-06-17T02:49:44.133467+00:00 [running]> on host 9b7c60adfed6
[2025-06-17T02:50:16.965+0000] {settings.py:363} DEBUG - Disposing DB connection pool (PID 228)
[2025-06-17T02:50:16.965+0000] {settings.py:250} DEBUG - Setting up DB connection pool (PID 228)
[2025-06-17T02:50:16.966+0000] {settings.py:298} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-06-17T02:50:17.024+0000] {taskinstance.py:1042} DEBUG - previous_execution_date was called
[2025-06-17T02:50:17.027+0000] {taskinstance.py:1845} DEBUG - Clearing XCom data
[2025-06-17T02:50:17.108+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-06-17T02:50:17.145+0000] {retries.py:91} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-06-17T02:50:17.188+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='globalsuperstore' AIRFLOW_CTX_TASK_ID='transform.transform_dim_shipmode' AIRFLOW_CTX_EXECUTION_DATE='2025-06-17T02:49:44.133467+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-17T02:49:44.133467+00:00'
[2025-06-17T02:50:17.189+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2025-06-17T02:50:17.190+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2025-06-17T02:50:17.191+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-17T02:50:17.301+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:50:17.310+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-06-17T02:50:17.312+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-17T02:50:17.313+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transform_dim_shipmode.py", line 9, in transform_dim_shipmode
    warehouse_operator.run_sql('TRUNCATE TABLE "warehouse"."dim_shipmode" RESTART IDENTITY CASCADE')
AttributeError: 'PostgresOperators' object has no attribute 'run_sql'
[2025-06-17T02:50:17.326+0000] {taskinstance.py:562} DEBUG - Task Duration set to 0.515981
[2025-06-17T02:50:17.330+0000] {taskinstance.py:584} DEBUG - Clearing next_method and next_kwargs.
[2025-06-17T02:50:17.331+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=globalsuperstore, task_id=transform.transform_dim_shipmode, run_id=manual__2025-06-17T02:49:44.133467+00:00, execution_date=20250617T024944, start_date=20250617T025016, end_date=20250617T025017
[2025-06-17T02:50:17.370+0000] {cli_action_loggers.py:88} DEBUG - Calling callbacks: []
[2025-06-17T02:50:17.371+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 445 for task transform.transform_dim_shipmode ('PostgresOperators' object has no attribute 'run_sql'; 228)
[2025-06-17T02:50:17.422+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-17T02:50:17.436+0000] {taskinstance.py:3461} DEBUG - Skip locked rows, rollback
[2025-06-17T02:50:17.437+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
